### PR TITLE
Friendships v1

### PR DESCRIPTION
**Pull request by AdfPizarro**
Implemented friendship methods

To
Send friendship request
View pending invitations
Accept or reject other users invitations
Prevent from inviting yourself, and send duplicated or redundant invitations

### CODE REVIEW

**Review by kevincappuccino — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey @AdfPizarro,  your project is looking really good, however, to accomplish as the actual project, you required to do these changes, listed below:
 
_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, to get more knowledge and have a better project to add at your portfolio.
 
 
## [REQUIRED CHANGES]
- [x] When we send a friend request, that option still is available, you should hide it;
- [x] Your project should have a button to invite user to friendship on users list page and on single user page;
- [x] The posts of my timeline should include posts written by me and my friends;
- [x] You have rubocop errors, please fix them;
- [x] Improve your readme.

## [OPTIONAL CHANGES]
- [ ] Improve the layout
<hr>
PS: I loved the name you used at the tests, high 5 🖐;

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you the very best and see you at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice work so far, team. 👍 
## However, there are some changes required 👀 🧰 🔨 🔧 

When testing in my local environment, I can't seem to be able to accept friend requests that I've sent from another user.

Please check that the friendship requests are properly received by other users when creating a new database. Try dropping your current database with `rails db:drop` and then creating a new one with `rails db:create` and `rails db:migrate`, and then follow these steps which I used to test your app:

1. Create a user `user1`
2. Log out and create a user `user2`
3. Send a friend request to `user1` as `user2`.
4. Log out and sign in as `user1`.

When I did this I was not able to see the `Accept Friendship` button beside `user2` on the `ALL USERS` list. Please fix this!

**[OPTIONAL]**

It would be nice to have a `Cancel Friendship Request` button as well, for when you want to retract your friendship request.

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by voscarmv** [comment]
Also, please note that you seem to be having trouble with your .github/workflows configuration. The automated tests don't seem to be triggering in this Pull Request:

image

This is a github bug which has been affecting forked repositories.

Please try this to fix the problem:

https://twitter.com/github/status/1321859709075394563

Cheers!

**Comment by AdfPizarro** [comment]
> 
> 
> Also, please note that you seem to be having trouble with your .github/workflows configuration. The automated tests don't seem to be triggering in this Pull Request:
> 
> image
> 
> This is a github bug which has been affecting forked repositories.
> 
> Please try this to fix the problem:
> 
> https://twitter.com/github/status/1321859709075394563
> 
> If this does not work, feel free to contact me on Slack, I might be able to help :)
> 
> Cheers!

Thanks for the advice

**Review by voscarmv — APPROVED** [review]
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
